dist: focal
language: python
python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
services:
  - docker
install:
  - pip install --upgrade -r test-requirements.txt
before_script:
  - ./bootstrap.sh
script: coverage run
after_success:
  - codecov
  - CODECLIMATE_REPO_TOKEN=ed39a2c039a29b0965bfdd243fea7caba2a83a4945bbd69fe95f506066754bd1 codeclimate-test-reporter
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 3.12
    tags: true
    all_branches: true
  password:
    secure: "ls9ja4J6bcirOvWVCvPAWboaOK6O0Pr/aZmHiifUYKEBqUg8D9PB7JyeXybMthXSx+jkHrFp6pL/IjYGrMYQ3gomZ+fsQTavNLxZxEHyLxDf7LVBxQ0KMNNh+GyF7qi9U749MlZBf9JgBFbAgnwCZRnlzCM8j7PxcFevYv4gouE="
